# Generated by Django 5.2.8 on 2026-08-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_gestiones_existentes(apps, schema_editor):
    Solicitud = apps.get_model("solicitudes", "Solicitud")
    Gestion = apps.get_model("gestion", "Gestion")
    existentes = set(Gestion.objects.values_list("solicitud_id", flat=True))
    nuevas = [
        Gestion(solicitud_id=solicitud_id)
        for solicitud_id in Solicitud.objects.values_list("id_solicitud", flat=True)
        if solicitud_id not in existentes
    ]
    Gestion.objects.bulk_create(nuevas, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('solicitudes', '0006_solicitud_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mensaje_paciente', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'motivo de rechazo',
                'verbose_name_plural': 'motivos de rechazo',
                'db_table': 'gestion_motivo_rechazo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=10)),
                ('prioridad_clinica', models.CharField(blank=True, choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=8)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_citacion', models.DateTimeField(blank=True, null=True)),
                ('intentos_contacto', models.PositiveSmallIntegerField(default=0)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('aviso_whatsapp_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, choices=[('AGENDADA', 'Agendada'), ('NO_ACEPTA', 'El paciente no acepta'), ('NO_CONTACTADO', 'No se logro contactar'), ('AVISADO_WHATSAPP', 'Avisado por WhatsApp'), ('SIN_AVISO', 'Sin aviso')], max_length=20)),
                ('contactado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_gestion', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_gestion', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion', to='solicitudes.solicitud')),
                ('motivo_rechazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gestiones', to='gestion.motivorechazo')),
            ],
            options={
                'verbose_name': 'gestion de solicitud',
                'verbose_name_plural': 'gestiones de solicitudes',
                'db_table': 'gestion_solicitud',
                'ordering': ['solicitud__date_solicitud'],
                'indexes': [models.Index(fields=['decision', 'cerrada_en'], name='gestion_dec_cierre_idx'), models.Index(fields=['fecha_decision'], name='gestion_fecha_dec_idx')],
            },
        ),
        migrations.RunPython(crear_gestiones_existentes, migrations.RunPython.noop),
    ]
