# Generated by Django 5.2.8 on 2026-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_motivo_rechazo_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='ultima_accion_contacto',
            field=models.CharField(blank=True, choices=[('NO_CONTESTA', 'No contesta'), ('WHATSAPP', 'WhatsApp'), ('AGENDADA', 'Agendada'), ('NO_ACEPTA', 'El paciente no acepta'), ('NO_CONTACTADO', 'No se logro contactar')], max_length=20),
        ),
    ]
