# Generated by Django 5.2.8 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_gestion_ultima_accion_contacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestion",
            name="ultimo_token_contacto",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
