# Generated by Django 5.2.8 on 2026-08-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_gestion_ultimo_token_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='ultimo_token_contacto',
        ),
        migrations.CreateModel(
            name='TokenContactoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('accion', models.CharField(choices=[('NO_CONTESTA', 'No contesta'), ('WHATSAPP', 'WhatsApp'), ('AGENDADA', 'Agendada'), ('NO_ACEPTA', 'El paciente no acepta'), ('NO_CONTACTADO', 'No se logro contactar')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_contacto', to='gestion.gestion')),
            ],
            options={
                'verbose_name': 'token de contacto',
                'verbose_name_plural': 'tokens de contacto',
                'db_table': 'gestion_token_contacto',
                'constraints': [models.UniqueConstraint(fields=('gestion', 'token', 'accion'), name='gestion_token_accion_uniq')],
            },
        ),
    ]
