# Generated by Django 5.2.8 on 2026-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_gestion_ultimo_token_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="motivorechazo",
            name="mensaje_paciente",
            field=models.TextField(
                help_text=(
                    "Solo el cuerpo. El saludo con el nombre, el centro y el "
                    "cierre los agrega el sistema."
                )
            ),
        ),
        migrations.CreateModel(
            name='PlantillaWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('cuerpo', models.TextField(help_text='Solo el cuerpo. El saludo con el nombre, el centro y el cierre los agrega el sistema.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'plantilla de WhatsApp',
                'verbose_name_plural': 'plantillas de WhatsApp',
                'db_table': 'gestion_plantilla_whatsapp',
                'ordering': ['clave'],
            },
        ),
    ]
