# Generated by Django 5.2.8 on 2026-08-28 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_seed_plantilla_whatsapp_y_limpia_motivos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('LLAMADA', 'Llamada telefonica'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('resultado', models.CharField(choices=[('NO_CONTESTA', 'No contesta'), ('WHATSAPP', 'WhatsApp'), ('AGENDADA', 'Agendada'), ('NO_ACEPTA', 'El paciente no acepta'), ('NO_CONTACTADO', 'No se logro contactar')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_contacto', to='gestion.gestion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_contacto_gestion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de contacto',
                'verbose_name_plural': 'registros de contacto',
                'db_table': 'gestion_registro_contacto',
                'ordering': ['-creado_en', '-pk'],
                'indexes': [models.Index(fields=['gestion', '-creado_en'], name='gestion_reg_contacto_idx')],
            },
        ),
    ]
