# Generated by Django 5.2.8 on 2026-08-28 12:17

from django.db import migrations


def canal_para_accion(accion):
    if accion == "WHATSAPP":
        return "WHATSAPP"
    return "LLAMADA"


def forwards(apps, schema_editor):
    TokenContactoGestion = apps.get_model("gestion", "TokenContactoGestion")
    RegistroContacto = apps.get_model("gestion", "RegistroContacto")
    for token in TokenContactoGestion.objects.all().order_by("creado_en", "pk"):
        registro = RegistroContacto.objects.create(
            gestion_id=token.gestion_id,
            canal=canal_para_accion(token.accion),
            resultado=token.accion,
            mensaje="",
            usuario_id=None,
        )
        RegistroContacto.objects.filter(pk=registro.pk).update(creado_en=token.creado_en)


def backwards(apps, schema_editor):
    TokenContactoGestion = apps.get_model("gestion", "TokenContactoGestion")
    RegistroContacto = apps.get_model("gestion", "RegistroContacto")
    for token in TokenContactoGestion.objects.all().order_by("creado_en", "pk"):
        RegistroContacto.objects.filter(
            gestion_id=token.gestion_id,
            resultado=token.accion,
            usuario__isnull=True,
            mensaje="",
            creado_en=token.creado_en,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_registro_contacto"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
