# Generated by Django 5.2.8 on 2026-08-28 12:17

from django.db import migrations


def canal_para_accion(accion):
    if accion == "WHATSAPP":
        return "WHATSAPP"
    return "LLAMADA"


def forwards(apps, schema_editor):
    TokenContactoGestion = apps.get_model("gestion", "TokenContactoGestion")
    RegistroContacto = apps.get_model("gestion", "RegistroContacto")
    registros = []
    for token in TokenContactoGestion.objects.all().order_by("creado_en", "pk"):
        registros.append(
            RegistroContacto(
                gestion_id=token.gestion_id,
                canal=canal_para_accion(token.accion),
                resultado=token.accion,
                mensaje="",
                usuario_id=None,
                creado_en=token.creado_en,
            )
        )
    RegistroContacto.objects.bulk_create(registros, batch_size=500)


def backwards(apps, schema_editor):
    RegistroContacto = apps.get_model("gestion", "RegistroContacto")
    RegistroContacto.objects.filter(usuario__isnull=True, mensaje="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_registro_contacto"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
