# Generated by Django 5.2.8 on 2026-09-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitud_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraClavePrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120)),
                ('texto_normalizado', models.CharField(editable=False, max_length=120, unique=True)),
                ('nivel', models.CharField(choices=[('URGENTE', 'Urgente'), ('MODERADA', 'Moderada')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'palabra clave de prioridad',
                'verbose_name_plural': 'palabras clave de prioridad',
                'db_table': 'solicitudes_palabra_clave_prioridad',
                'ordering': ['nivel', 'texto_normalizado'],
            },
        ),
    ]
